"""added role

Revision ID: 65389e8d0aab
Revises: 2c7f47b2c303
Create Date: 2022-03-08 19:06:17.063730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65389e8d0aab'
down_revision = '2c7f47b2c303'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teamName', sa.String(length=150), nullable=True),
    sa.Column('imgURL', sa.String(length=255), nullable=True),
    sa.Column('teamMemberOne', sa.Integer(), nullable=False),
    sa.Column('teamMemberTwo', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['teamMemberOne'], ['users.id'], ),
    sa.ForeignKeyConstraint(['teamMemberTwo'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('role', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_table('teams')
    # ### end Alembic commands ###
